SaleManagement/SaleManagement/Controllers/StatsController.cs
using Newtonsoft.Json;
using SaleManagement.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SaleManagement.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StatsController : Controller
    {

        private QLBHContext db = new QLBHContext();

        #region ACTION RESULT
        // GET: Stats
        public ActionResult Index()
        {
            DateTime thisweek = DateTime.Now.AddDays(-6);
            var lst = db.OrderDetailViewModel.Where(s => DateTime.Compare(s.OrderViewModel.DateOfOrder, thisweek) >= 0
                                            && DateTime.Compare(s.OrderViewModel.DateOfOrder, DateTime.Now) <= 0)
                                            .GroupBy(s => s.ProductID).Select(s => new
                                            {
                                                ProductID = s.Key,
                                                ProductName = s.Select(a => a.ProductName).FirstOrDefault(),
                                                Quantity = s.Sum(a => (int?)a.Quantity ?? 0)
                                            }).OrderByDescending(s => s.Quantity).ToList();
            if (lst.Count() > 0)
            {
                ViewBag.Product1 = lst[0].ProductName;
                ViewBag.Quantity1 = lst[0].Quantity;
            }
            if (lst.Count() > 1)
            {
                ViewBag.Product2 = lst[1].ProductName;
                ViewBag.Quantity2 = lst[1].Quantity;
            }
            if (lst.Count() > 2)
            {
                ViewBag.Product3 = lst[2].ProductName;
                ViewBag.Quantity3 = lst[2].Quantity;
            }
            if (lst.Count() > 3)
            {
                ViewBag.Product4 = lst[3].ProductName;
                ViewBag.Quantity4 = lst[3].Quantity;
            }
            return View();
        }
        //1.0 list for year 
        public ActionResult List()
        {
            return View();
        }
        //1.1 list for month
        public ActionResult ListMonth()
        {
            return View();
        }
        //1.2 list for day
        public ActionResult ListDay()
        {
            return View();
        }
        //1.3 list day by day
        public ActionResult ListDayByDay()
        {
            return View();
        }
        //1.4 list for customer
        public ActionResult ListCustomer()
        {
            return View();
        }
        // GET: OrderViewModel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OrderViewModel hds = db.OrderViewModels.Find(id);
            if (hds == null)
            {
                return HttpNotFound();
            }


            return View(hds);
        }
        //2.0 graph for DT
        public ActionResult Graph()
        {

            return View();
        }
        //2.1 graph for So luong san pham
        public ActionResult GraphProductQuantity()
        {
            return View();
        }
        //2.2 Graph SanPham
        public ActionResult GraphProduct()
        {
            return View();
        }
        //2.3 Graph Thanh Khoản
        public ActionResult GraphLiquidity()
        {
            return View();
        }
        #endregion
        #region JSON
        // A. Index Thanh Khoan
        public JsonResult LiquidityOfWeek()
        {

            var thisweek = DateTime.Now.AddDays(-6);
            var lastweek = thisweek.AddDays(-7);
            //thanh khoản tuan nay
            var lst = db.OrderViewModels.Where(s => DateTime.Compare(s.DateOfOrder, DateTime.Now) <= 0
                                        && DateTime.Compare(s.DateOfOrder, thisweek) >= 0).Select(s => new
                                        {
                                            Date = s.DateOfOrder,
                                            Time = s.DateOfOrder.Day + "/" + s.DateOfOrder.Month,
                                            Liquidity = s.OrderID
                                        }).GroupBy(s => s.Time).OrderBy(a => a.Key).Select(s => new
                                        {
                                            Time = s.Key,
                                            Date = s.Select(a => a.Date).FirstOrDefault(),
                                            Liquidity = s.Select(a => a.Liquidity).Count(),
                                            LiquidityLastWeek = 0
                                        }).ToList();
            //thanh khoan tuan truoc
            var lst1 = db.OrderViewModels.Where(s => DateTime.Compare(s.DateOfOrder, thisweek) < 0
                                       && DateTime.Compare(s.DateOfOrder, lastweek) >= 0).Select(s => new
                                       {
                                           Date = s.DateOfOrder,
                                           Time = s.DateOfOrder.Day + "/" + s.DateOfOrder.Month,
                                           Liquidity = s.OrderID
                                       }).GroupBy(s => s.Time).OrderBy(a => a.Key).Select(s => new
                                       {
                                           Time = s.Key,
                                           Date = s.Select(a => a.Date).FirstOrDefault(),
                                           Liquidity = s.Select(a => a.Liquidity).Count()
                                       }).ToList();

            List<object> lstObj = new List<object>();
            
            for (DateTime i = thisweek, j = lastweek; DateTime.Compare(i, DateTime.Now) <= 0 && DateTime.Compare(j, thisweek) < 0; i = i.AddDays(1), j = j.AddDays(1))
            {

                var tmp = lst.Where(s => s.Date.Day == i.Day).Select(s => s).FirstOrDefault();
                var tmp2 = lst1.Where(s => s.Date.Day == j.Day).Select(s => s).FirstOrDefault();


                if (tmp != null || tmp2 != null)
                {
                    int x1 = 0, x2 = 0;
                    if (tmp != null)
                        x1 = tmp.Liquidity;
                    if (tmp2 != null)
                        x2 = tmp2.Liquidity;
                    var x = new
                    {
                        Day = i.Day,
                        Time = i.Day + "/" + i.Month,
                        Liquidity = x1,
                        LiquidityLastWeek = x2
                    };
                    lstObj.Add(x);
                }
                else
                {
                    var x = new
                    {
                        Day = i.Day,
                        Time = i.Day + "/" + i.Month,
                        Liquidity = 0,
                        LiquidityLastWeek = 0
                    };
                    lstObj.Add(x);
                }
            }
            return Json(lstObj.ToList(), JsonRequestBehavior.AllowGet);
        }
        //A. Index Doanh Thu Theo Tuan
        public JsonResult TurnoverOfWeek()
        {

            var thisweek = DateTime.Now.AddDays(-6);
            var lastweek = thisweek.AddDays(-7);
            //doanh thu tuan nay
            var lst = db.OrderViewModels.Where(s => DateTime.Compare(s.DateOfOrder, DateTime.Now) <= 0
                                        && DateTime.Compare(s.DateOfOrder, thisweek) >= 0).Select(s => new
                                        {
                                            Date = s.DateOfOrder,
                                            Time = s.DateOfOrder.Day + "/" + s.DateOfOrder.Month,
                                            Turnover = s.Total
                                        }).GroupBy(s => s.Time).OrderBy(a => a.Key).Select(s => new
                                        {
                                            Time = s.Key,
                                            Date = s.Select(a => a.Date).FirstOrDefault(),
                                            Turnover = s.Sum(a => (int?)a.Turnover) ?? 0,
                                            TurnoverLastWeek = 0
                                        }).ToList();
            //doanh thu tuan truoc
            var lst1 = db.OrderViewModels.Where(s => DateTime.Compare(s.DateOfOrder, thisweek) <= 0
                                       && DateTime.Compare(s.DateOfOrder, lastweek) > 0).Select(s => new
                                       {
                                           Date = s.DateOfOrder,
                                           Time = s.DateOfOrder.Day + "/" + s.DateOfOrder.Month,
                                           Turnover = s.Total
                                       }).GroupBy(s => s.Time).OrderBy(a => a.Key).Select(s => new
                                       {
                                           Time = s.Key,
                                           Date = s.Select(a => a.Date).FirstOrDefault(),
                                           Turnover = s.Sum(a => (int?)a.Turnover) ?? 0
                                       }).ToList();

            List<object> lstObj = new List<object>();
            var r = DateTime.Compare(DateTime.Parse("4/30/2015"), DateTime.Parse("5/1/2015"));
            
            for (DateTime i = thisweek, j = lastweek; DateTime.Compare(i, DateTime.Now) <= 0 && DateTime.Compare(j, thisweek) < 0; i = i.AddDays(1), j = j.AddDays(1))
            {

                var tmp = lst.Where(s => s.Date.Day == i.Day).Select(s => s).FirstOrDefault();
                var tmp2 = lst1.Where(s => s.Date.Day == j.Day).Select(s => s).FirstOrDefault();
                int x1 = 0, x2 = 0;
                
                if (tmp != null || tmp2 != null)
                {
                    if (tmp != null)
                    {

SaleManagement/SaleManagement/Views/Bill/Create.cshtml
@model  IEnumerable<string>
@{
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}
@{
    ViewBag.Title = "Lập Hóa Đơn";
}
<div class="stat-content-title white" style="box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);">
    <span></span>
    Bán Hàng
</div>
<hr />
<body onload="PageOnload()" ng-app="CreateBill">
    <div class="container-fix" style="margin-top:50px;" ng-controller="CreateBillController">
        <div class="row">          
            <div class="col-sm-4" style="padding-right:0px">
                <div class="table-content1">
                    <div class="row">
                        <div class="col-sm-6" id="margin-bottom">
                            <input class="input-full-width" id="ProductID" onkeypress="return enterAsTab();" type="text" tabindex="2" autofocus />
                        </div>
                        <div class="col-sm-6" id="margin-bottom">
                          @*  <input class="k-textbox input-full-width" id="txtSoLuong" min="0" onkeypress="return enterAsTab();" tabindex="3" placeholder="Số lượng..." />*@
                            <button type="button" class="k-button k-primary pull-right" onclick="btnThem_Onclick()" tabindex="3">&nbsp;&nbsp;&nbsp;&nbsp;Thêm &nbsp;&nbsp;&nbsp;&nbsp;</button>
                        </div>                                           
                    </div>
                    <div class="row" style="padding-left:20px;padding-right:15px;margin-top:10px" >
                       
                    </div>
                    <hr class="hr-style"/>
                    <div class="row">
                        <div class="col-sm-6" id="margin-bottom" >
                            <input class="input-full-width" id="CustomerID" type="text" ng-blur="showInfoCus()" onkeypress="return enterAsTab();" tabindex="1" placeholder="Mã khách hàng..."  />
                        </div>
                        <div class="col-sm-6" id="margin-bottom">
                            <table style="width:100%">
                                <tr>
                                    <td class="info-custumer">
                                        Thông tin khách hàng
                                    </td>
                                </tr>
                                <tr>
                                    <td style="border:1px solid whitesmoke">
                                        <table>
                                            <tbody id="info">
                                                <p ng-bind="Khachle"></p>
                                                <p ng-bind="CustomerID2"></p>
                                                <p ng-bind="CustomerName"></p>
                                                <p ng-bind="Birthday"></p>
                                                <p ng-bind="Sex"></p>
                                                <p ng-bind="PhoneNumber"></p>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </table>

                        </div>
                        @*<div class="col-sm-2">

                        </div>*@
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="table-content1 table-responsive">
                    <table id="laphoadon" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="k-label text-center">
                                    STT
                                </th>

                                <th class="k-label text-center">
                                    Tên Sản Phẩm
                                </th>
                                <th class="k-label text-center">
                                    Số Lượng
                                </th>
                                <th class="k-label text-center">
                                    Thành Tiền
                                </th>
                                <th class="k-label text-center">
                                    Thao tác
                                </th>
                            </tr>

                        </thead>
                        <tbody class="text-center" id="laphoadon"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
    var myModel = angular.module("CreateBill", []);
    myModel.controller("CreateBillController", function ($scope, $http) {
        $scope.Khachle = "Khách Lẻ";
        $scope.showInfoCus = function () {
            var tmp = $("#CustomerID").val();
            if (tmp != null)
                var CustomerID = parseInt(tmp);
            // if (!isNaN(CustomerID)) CustomerID = null;
            var req = {
                url: '/bill/checkCustomerID',
                data: { CustomerID: CustomerID },
                headers: { dataType: 'application/json; charset=utf-8' },
                method: 'post'
            }
            // alert(CustomerID);
            $http(req).
                success(function (DataSource) {
                    if (DataSource.info == "ok") {
                        var sex =DataSource.Sex?"Nam":"Nữ";
                        $scope.Khachle = "";
                        $scope.CustomerID2 = "Mã KH: " + DataSource.CustomerID;
                        $scope.CustomerName = "Tên KH: " + DataSource.CustomerName;
                        $scope.Sex = "Giới Tính: " +sex ;
                        $scope.PhoneNumber = "SĐT: " + DataSource.PhoneNumber;
                        // console.log(DataSource);
                    } else {
                        $scope.Khachle = "Khách Lẻ";
                        $scope.CustomerID2 = "";
                        $scope.CustomerName = "";
                        $scope.Sex = "";
                        $scope.PhoneNumber = "";
                    }
                }).
                error(function (DataSource) {
                    // alert(DataSource);
                });
        }
    });
</script>
@Scripts.Render("~/bundles/Bill")
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SaleManagement/SaleManagement/Views/Bill/Details.cshtml
@{
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}
@model SaleManagement.Models.OrderViewModel
@{
    ViewBag.Title = "Thông tin hóa đơn";
}
@*<div class="container">
    <div id="printableArea">
        <div class="contain-bill">
            <div class="contain-logo">
                <h6><b>@Html.DisplayFor(model => model.StoreName)</b></h6>
            </div>
            <div class="row_HD">
                <div class="col-xs-8">@Html.DisplayFor(model => model.BranchName)</div>
                <div class="col-xs-8">@Html.DisplayFor(model => model.BranchAddress)</div>
                <div class="col-sx-4">Logo</div>
            </div>
            <div class="contain-bill1">
                HÓA ĐƠN BÁN LẺ
            </div>
            <div class="contain-ThongtinHD">
                <div class="row_HD">
                    <div class="col-xs-6">@Html.DisplayNameFor(model => model.DateOfOrder) :</div>
                    <div class="col-xs-6">@Html.DisplayFor(model => model.DateOfOrder)</div>
                </div>
                <div class="row_HD">
                    <div class="col-xs-6">@Html.DisplayNameFor(model => model.OrderID) :</div>
                    <div class="col-xs-6">@Html.DisplayFor(model => model.OrderID)</div>
                </div>

                <div class="row_HD">
                    <div class="col-xs-6">Tên nhân viên :</div>
                    <div class="col-xs-6">@Html.DisplayFor(modelItem => modelItem.EmployeeName)</div>
                </div>
                <div class="row_HD">
                    <div class="col-xs-6">@Html.DisplayNameFor(model => model.CustomerID) :</div>
                    <div class="col-xs-6">Khách lẻ</div>
                </div>
            </div>
            <div>----------------------------------</div>
            <table class="contain-table">
                <tr class="contain-table-row">
                    <th>TênSP</th>
                    <th>
                    <th>SL</th>
                    <th>@Html.DisplayNameFor(h => h.Quantity)₫</th>
                    <th>KM</th>
                    <th>@Html.DisplayNameFor(h => h.Discount) ₫</th>

                </tr>
                @foreach (var item in Model.OrderDetailViewModels)
                {
                    <tr class="contain-table-row-noborder">
                        <td style="width:99px">@Html.DisplayFor(h => item.ProductName)</td>
                        <td>@Html.DisplayFor(h => item.Quantity)</td>
                        <td>@Html.DisplayFor(h => item.ProductPrice)</td>
                        <td>@Html.DisplayFor(h => item.ProductDiscount)%</td>
                        <td>@Html.DisplayFor(h => item.Price)</td>
                    </tr>
                }
            </table>

            <div class=" contain-ThongtinHD">
                <div class="row_HD">
                    <div class="col-xs-6">Tổng Số Lượng :</div>
                    <div class="col-xs-6">@Html.DisplayFor(s=>s.Quantity)</div>
                </div>
                <div class="row_HD">
                    <div class="col-xs-6">Tổng Tiền Khuyến Mãi :</div>
                    <div class="col-xs-6">@Html.DisplayFor(s=>s.Discount)</div>
                </div>

                <div class="row_HD">
                    <div class="col-xs-6">Tổng Tiền :</div>
                    <div class="col-xs-6">@Html.DisplayFor(s=>s.Total)</div>
                </div>
            </div>
            <div>----------------------------------</div>

            <div class="contain-bill1">
                <h6>(Giá trên đã bao gồm thuế GTGT)</h6>
                <h6><b>Cám ơn và hẹn gặp lại quý khách!</b></h6>
            </div>
        </div>
    </div>*@
<div class="row row-margin-bill-preview">
        <div id="printableArea">
            <div class="contain-bill">
                <div class="contain-logo">
                    <h6><b>@Html.DisplayFor(model => model.StoreName)</b></h6>
                </div>
                <div class="row_HD">
                    <div class="col-xs-8">@Html.DisplayFor(model => model.BranchName)</div>
                    <div class="col-xs-8">@Html.DisplayFor(model => model.BranchAddress)</div>
                    @*<div class="col-sx-4">Logo</div>*@
                </div>
                <div class="contain-bill1">
                    HÓA ĐƠN BÁN LẺ
                </div>
                <div class="contain-ThongtinHD">
                    <div class="row_HD">
                        <div class="col-xs-6">@Html.DisplayNameFor(model => model.DateOfOrder) :</div>
                        <div class="col-xs-6">@Html.DisplayFor(model => model.DateOfOrder)</div>
                    </div>
                    <div class="row_HD">
                        <div class="col-xs-6">@Html.DisplayNameFor(model => model.OrderID) :</div>
                        <div class="col-xs-6">@Html.DisplayFor(model => model.OrderID)</div>
                    </div>

                    <div class="row_HD">
                        <div class="col-xs-6">Tên nhân viên :</div>
                        <div class="col-xs-6">@Html.DisplayFor(modelItem => modelItem.EmployeeName)</div>
                    </div>
                    <div class="row_HD">
                        <div class="col-xs-6">Khách Hàng:</div>
                        <div class="col-xs-6">@Html.DisplayFor(s=>s.CustomerName)</div>
                    </div>
                </div>
                <div>----------------------------------</div>
                <table class="contain-table">
                    <tr class="contain-table-row">
                        <th>TênSP</th>
                        <th>SL</th>
                        <th>@Html.DisplayNameFor(h => h.OrderDetailViewModels.First().ProductPrice)₫</th>
                        <th>KM</th>
                        <th>@Html.DisplayNameFor(h => h.OrderDetailViewModels.First().Price) ₫</th>

                    </tr>
                    @foreach (var item in Model.OrderDetailViewModels)
                    {
                        <tr class="contain-table-row-noborder">
                            <td style="width:99px">@Html.DisplayFor(h => item.ProductName)</td>
                            <td>@Html.DisplayFor(h => item.Quantity)</td>
                            <td>@Html.DisplayFor(h => item.ProductPrice)</td>
                            <td>@Html.DisplayFor(h => item.ProductDiscount)%</td>
                            <td>@Html.DisplayFor(h => item.Price)</td>
                        </tr>
                    }
                </table>

                <div class=" contain-ThongtinHD">
                    <div class="row_HD">
                        <div class="col-xs-6">Tổng Số Lượng :</div>
                        <div class="col-xs-6">@Html.DisplayFor(a=>a.Quantity)</div>
                    </div>
                    <div class="row_HD">
                        <div class="col-xs-6">Tổng Tiền :</div>
                        <div class="col-xs-6">@Html.DisplayFor(a=>a.Total)</div>
                    </div>
                    <div class="row_HD">
                        <div class="col-xs-6">Tổng Tiền Khuyến Mãi :</div>
                        <div class="col-xs-6">@Html.DisplayFor(a=>a.Discount)</div>
                    </div>
                    <div class="row_HD">
                        <div class="col-xs-6">Tổng Tiền Khách Trả:</div>
                        <div class="col-xs-6">@Html.DisplayFor(h => h.Total)</div>
                    </div>
                </div>
                <div>----------------------------------</div>
             
                <div class="contain-bill1">
                    <h6>(Giá trên đã bao gồm thuế GTGT)</h6>
                    <h6><b>Cám ơn và hẹn gặp lại quý khách!</b></h6>
                </div>
            </div>
        </div>
       
</div>

    <div class="contain-logo">
        <button type="submit" onclick="printContent('printableArea')" class=" btn btn-default">
            <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
            In Hóa Đơn
        </button>
        
        @Html.ActionLink("Trở Về", "listday", "Stats", null, new { @class = "btn btn-default" })
    </div>
</div>
    


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}