SaleManagement/SaleManagement/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SaleManagement.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
namespace SaleManagement.Controllers
{
    [Authorize(Roles = "Accountant,Admin")]
    public class ShoppingCardItem
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
        //khuyen mai
        public double Discount
        {
            get
            {
                return (Math.Round(double.Parse(((Quantity * Product.Price) * Product.Discount * 0.01).ToString())));
            }
        }
        //thue
        public double Tax
        {
            get
            {
                return (Math.Round(double.Parse(((Product.Price * Quantity
                    * Product.Tax * 0.01).ToString()))));
            }
        }
        public double TotalValue
        {
            get { return (Quantity * Product.Price); }
        }
        public double Value
        {
            get { return (Quantity * Product.Price) + Tax - Discount; }
        }
        public double Prepay { get; set; }

    }
    [Authorize(Roles = "Accountant,Admin")]
    public class ShoppingCard
    {
        public int? CustomerID;
        private List<ShoppingCardItem> CardItems = new List<ShoppingCardItem>();
        public List<ShoppingCardItem> Items
        {
            get { return CardItems; }
        }
        public double TotalValue
        {
            get { return Items.Sum(i => i.Value); }
        }

        public double TotalValue2()
        {
            return Items.Sum(i => i.TotalValue);
        }

        public void AddItem(string ProductID, int quantity)
        {
            ShoppingCardItem item = Items.Where(i => i.Product.ProductID.ToLower() == ProductID.ToLower()).FirstOrDefault();
            if (item == null)
            {
                QLBHContext db = new QLBHContext();
                var p = db.Products.Single(p1 => p1.ProductID.ToLower() == ProductID.ToLower());
                ShoppingCardItem shopItem = new ShoppingCardItem()
                {
                    Product = p,
                    Quantity = quantity
                };
                CardItems.Add(shopItem);
            }
            else
            {
                item.Quantity += quantity - item.Quantity;
            }
        }
        public void RemoveItem(string ProductID)
        {
            ShoppingCardItem item = Items.Single(i => i.Product.ProductID == ProductID);
            Items.Remove(item);

        }
        public void Clear()
        {
            CardItems.Clear();
        }
    }


    public class BillController : Controller
    {
        private static QLBHContext db = new QLBHContext();
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult CheckQuantity(int Quantity, string ProductID)
        {
            var pro = db.Products.Find(ProductID);
            if (pro.Quantity >= Quantity)
            {
                var infor = new { infor = "ok" };
                return Json(infor, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var infor = new { infor = pro.Quantity };
                return Json(infor, JsonRequestBehavior.AllowGet);
            }
        }
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult CancelOrder()
        {
            getShopingCard().Clear();
            string result = "{result:true}";
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = "Accountant,Admin")]
        public ShoppingCard getShopingCard()
        {
            ShoppingCard shopCard = (ShoppingCard)Session["shoppingcard"];
            if (shopCard == null)
            {
                shopCard = new ShoppingCard();
                Session["shoppingcard"] = shopCard;
            }
            return shopCard;
        }
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult AddToCard(string ProductID, int Quantity)
        {
            getShopingCard().AddItem(ProductID, Quantity);
            return Json(getShopingCard().Items.Select(s => new { ProductName = s.Product.ProductName, ProductID = s.Product.ProductID, Quantity = s.Quantity, Price = s.Value }).ToList(), JsonRequestBehavior.AllowGet);



        }
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult getShoppingCardItems()
        {
            return Json(getShopingCard().Items.Select(s => new { ProductName = s.Product.ProductName, ProductID = s.Product.ProductID, Quantity = s.Quantity, Price = s.Value }).ToList(), JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult RemoveShoppingCardItem(string ProductID)
        {
            ShoppingCard shop = getShopingCard();
            shop.RemoveItem(ProductID);
            return Json(getShopingCard().Items.Select(s => new { ProductName = s.Product.ProductName, ProductID = s.Product.ProductID, Quantity = s.Quantity, Price = s.Value }).ToList(), JsonRequestBehavior.AllowGet);
        }


        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult CheckProductID(string ProductID)
        {
            var pro = db.Products.Where(p => p.ProductID.ToLower() == ProductID.ToLower()).Select(p => p).FirstOrDefault();
            if (pro != null)
            {
                var infor = new { infor = "true" };
                return Json(infor, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var infor = new { infor = "Invalidate" };
                return Json(infor, JsonRequestBehavior.AllowGet);
            }
        }
         [Authorize(Roles = "Accountant,Admin")]
        public ActionResult CheckCustomerID(int? CustomerID)
        {
            var shopping = getShopingCard();
            var lst = db.Customers.Where(s => s.CustomerID == CustomerID).Select(s => s).FirstOrDefault();
            if (lst != null)
            {
                shopping.CustomerID = CustomerID; ;
                var infor = new { info = "ok", CustomerID = lst.CustomerID, CustomerName = lst.LastName + " " + lst.MiddleName + " " + lst.FirstName, PhoneNumber = lst.PhoneNumber , Birthday=lst.Birthday,Sex= lst.Sex};
                return Json(infor, JsonRequestBehavior.AllowGet);
            }
            else
            {
                shopping.CustomerID = 1;
                var infor = new { info = "Khách lẻ" };
                return Json(infor, JsonRequestBehavior.AllowGet);
            }
        }
        [Authorize(Roles = "Accountant,Admin")]
        
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult Create()
        {
            return View();
        }
        //GET
        [Authorize(Roles = "Accountant,Admin")]
        public ActionResult Preview()
        {
            db = new QLBHContext();
            Order hd = new Order();
            OrderViewModel hdView = new OrderViewModel();
            var lstSession = (ShoppingCard)Session["shoppingcard"];
            if (lstSession != null)
            {
                OrderDetail cthd = new OrderDetail();
                OrderDetailViewModel cthdView = new OrderDetailViewModel();
                //HOA DON
                // add Order
                var maxOrder = db.Orders.Select(s => s.OrderID);
                if (maxOrder.Count() == 0)
                {
                    hd.OrderID = 1;
                }
                else
                {
                    hd.OrderID = maxOrder.Max() + 1;
                }
                hd.CustomerID = lstSession.CustomerID ;
                if (hd.CustomerID == null)
                    hd.CustomerID = 1;
                var kh = db.Customers.Find(hd.CustomerID);

                if (kh != null)
                {
                    Point point = new Point();
                    point = db.Points.First();
                    kh.Point += (int)lstSession.TotalValue /( point.PointValue/point.PointRatio);
                }
                
                Session["OrderID"] = hd.OrderID;
                var Employee = db.Users.Find(User.Identity.GetUserId());
                //adding order
                hd.BranchID = Employee.BranchID;
                hd.DateOfOrder = DateTime.Now;
                hd.EmployeeID = Employee.Id;
                db.Orders.Add(hd);
                //adding order view
                db.SaveChanges();
                //
                foreach (var item in lstSession.Items)
                {
                    cthd = new OrderDetail();
                    cthd.OrderID = hd.OrderID;
                    cthd.ProductID = item.Product.ProductID;
                    cthd.Quantity = item.Quantity;
                    //price for every product
                    cthd.Price = item.Value;
                    db.OrderDetails.Add(cthd);
                }
                db.SaveChanges();
                //cap nhat lai thong tin chi tiet qua hoa don
                //Tổng số lượng
                hd.Quantity = lstSession.Items.Select(s => s.Quantity).Sum();
                // tổng tiền khuyến mãi
                hd.Discount = lstSession.Items.Select(s => s.Discount).Sum();
                //Tổng tiền - bao gồm khuyến mãi
                hd.Total = lstSession.TotalValue;

               
                //Trừ số lượng sản phẩm đã mua
                Product sp;
                foreach (var item in lstSession.Items)
                {
                    sp = new Product();
                    sp = db.Products.Find(item.Product.ProductID);
                    sp.Quantity -= item.Quantity;

                }
                db.SaveChanges();

                //view order

                
                hdView.OrderID = hd.OrderID;
                hdView.CustomerID = hd.CustomerID;

SaleManagement/SaleManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Content/img/favicon.ico">
    <title>Quản Lý Bán Hàng </title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo/css")
    @Styles.Render("~/Content/homepage/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/homepage")


</head>
<body>
    <!-- NAVBAR  ================================================== -->
    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse navbar-fixed-top" style="border-radius:0px">
                <div class="container-fluid">
                    <div class="navbar-header" style="text-align:center;">
                        <button type="button" class="navbar-toggle collapsed" style="text-align:center;" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <img style="max-width:100px; vertical-align:middle; max-height:40px;margin-top:5px" src="~/Content/img/logotest.png">
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <!--Trang chủ-->
                            <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
                            @if (Request.IsAuthenticated && User.IsInRole("Accountant"))
                            {
                                <li> @Html.ActionLink("Bán Hàng", "Create", "Bill")</li>
                            }
                            <!--Dropdown -->
                            @if (Request.IsAuthenticated && User.IsInRole("Storekeeper"))
                            {
                                <li class="dropdown">
                                    <!--Tên Dropdown-->
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Quản Lý Kho <span class="caret"></span></a>
                                    <!--Item con-->
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="menuitem">@Html.ActionLink("Quản Lý Sản Phẩm", "Index", "Product")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Loại Sản Phẩm", "Index", "Category")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Nhà Cung Cấp", "Index", "Provider")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Chi Tiết Nhà Cung Cấp", "Index", "ProviderDetail")</li>
                                        <li role="presentation">@Html.ActionLink("Cập Nhật Thông Tin Từ File", "UploadFile", "Product")</li>
                                    </ul>
                                </li>
                                <li>@Html.Action("GetNotify", "Home")</li>
                            }

                            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="dropdown">
                                    <!--Tên Dropdown-->
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Quản Lý Kho <span class="caret"></span></a>
                                    <!--Item con-->
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="menuitem">@Html.ActionLink("Quản Lý Sản Phẩm", "Index", "Product")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Loại Sản Phẩm", "Index", "Category")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Nhà Cung Cấp", "Index", "Provider")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Chi Tiết Nhà Cung Cấp", "Index", "ProviderDetail")</li>
                                        <li role="presentation">@Html.ActionLink("Cập Nhật Thông Tin Từ File", "UploadFile", "Product")</li>
                                    </ul>
                                </li>

                                <li> @Html.ActionLink("Bán Hàng", "Create", "bill")</li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"  aria-expanded="false">Quản Lý Thông Tin<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="presentation">@Html.ActionLink("Quản Lý Phòng Ban", "Index", "Department")</li>
                                        <li role="menuitem">@Html.ActionLink("Quản Lý Nhân Viên", "Index", "Account")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Khách Hàng", "Index", "Customer")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Loại Khách Hàng", "Index", "CustomerCategory")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Phân Quyền", "authorize", "account")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Chi Nhánh", "Index", "Branch")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Cửa Hàng", "Index", "Store")</li>
                                        <li role="presentation">@Html.ActionLink("Quản Lý Điểm Khách Hàng", "EditPoint", "Customer")</li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                       @Html.ActionLink("Thống Kê", "Index", "stats")
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="presentation" class="dropdown-header text-center">Danh Sách</li>
                                        <li role="presentation">@Html.ActionLink("Hóa Đơn(Tùy Chọn)", "ListDayByDay", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Hóa Đơn (Theo Ngày)", "ListDay", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Hóa Đơn (Theo Tháng)", "ListMonth", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Hóa Đơn (Theo Năm)", "List", "stats")</li>
                                        <li role="presentation" class="divider"></li>
                                        <li role="presentation" class="dropdown-header text-center">Biểu Đồ</li>
                                        <li role="presentation">@Html.ActionLink("Tổng Quan", "index", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Doanh Thu", "Graph", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Sản Phẩm", "GraphProduct", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Số Lượng Sản Phẩm", "GraphProductQuantity", "stats")</li>
                                        <li role="presentation">@Html.ActionLink("Thanh Khoản", "GraphLiquidity", "stats")</li>
                                    </ul>
                                </li>
                                <li>
                                    @Html.Action("GetNotify", "Home")
                                </li>
                            }
                        </ul>
                        <ul class="nav navbar-nav" style="float:right">

                            <li>
                                <ul class="nav navbar-nav">@Html.Partial("_LoginPartial")</ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </div>
    <!-- NAVBAR ================================================== -->


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy ThePhuongSolutions @DateTime.Now.Year </p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)

</body>
</html>